### ISSUE TITLE
ObjectSet should be called UniqueObjectSet

### ISSUE THREAD

**Issue by Bilge** [malarzm/collections#5]
According to the documentation this collection guarantees a unique set but nowhere does the word "unique" actually get mentioned. I believe `UniqueObjectSet` or `UniqueSet` is a better name because it conveys this crucial information immediately. I am not sure what `ObjectSet` would mean besides a set of objects.

**Comment by malarzm** [comment]
I took a page from math, and following quote is from [wiki](https://en.wikipedia.org/wiki/Set_%28mathematics%29)

> In mathematics, a set is a collection of distinct objects

:)

**Comment by Bilge** [comment]
k lol
