### ISSUE TITLE
AbstractCollection is missing methods required to fullfill Collection contract.

### ISSUE THREAD

**Issue by trq** [malarzm/collections#9]
`Malarzm\Collections\AbstractCollection` appears to be missing the methods `add`, `set`, `remove` and `removeElement` it requires to implement the interface `Doctrine\Common\Collections\Collection`.

**Comment by malarzm** [comment]
Indeed, I must have not included them as all other classes were meant to have their own logic for each of not declared methods. If you need these methods with default behaviour I'm open for accepting a PR :)

**Comment by malarzm** [comment]
@trq I've added new `ArrayCollection` with default implementation
